
package myhealthylife.dataservice.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataService", targetNamespace = "http://soap.dataservice.myhealthylife/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataService {


    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.RegisterResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/registerRequest", output = "http://soap.dataservice.myhealthylife/DataService/registerResponse")
    public Person register(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @return
     *     returns myhealthylife.dataservice.soap.People
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "listPeople", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.ListPeople")
    @ResponseWrapper(localName = "listPeopleResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.ListPeopleResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/listPeopleRequest", output = "http://soap.dataservice.myhealthylife/DataService/listPeopleResponse")
    public People listPeople();

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetPersonResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/getPersonRequest", output = "http://soap.dataservice.myhealthylife/DataService/getPersonResponse")
    public Person getPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.UpdatePersonResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/updatePersonRequest", output = "http://soap.dataservice.myhealthylife/DataService/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "idPerson", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.DeletePersonResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/deletePersonRequest", output = "http://soap.dataservice.myhealthylife/DataService/deletePersonResponse")
    public long deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.CurrentHealth
     */
    @WebMethod
    @WebResult(name = "currentHealth", targetNamespace = "")
    @RequestWrapper(localName = "getCurrentHealth", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetCurrentHealth")
    @ResponseWrapper(localName = "getCurrentHealthResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetCurrentHealthResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/getCurrentHealthRequest", output = "http://soap.dataservice.myhealthylife/DataService/getCurrentHealthResponse")
    public CurrentHealth getCurrentHealth(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Measure
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "saveMeasure", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.SaveMeasure")
    @ResponseWrapper(localName = "saveMeasureResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.SaveMeasureResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/saveMeasureRequest", output = "http://soap.dataservice.myhealthylife/DataService/saveMeasureResponse")
    public Measure saveMeasure(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Measure arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Measure
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "getMeasure", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetMeasure")
    @ResponseWrapper(localName = "getMeasureResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetMeasureResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/getMeasureRequest", output = "http://soap.dataservice.myhealthylife/DataService/getMeasureResponse")
    public Measure getMeasure(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Measure
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "updateMeasure", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.UpdateMeasure")
    @ResponseWrapper(localName = "updateMeasureResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.UpdateMeasureResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/updateMeasureRequest", output = "http://soap.dataservice.myhealthylife/DataService/updateMeasureResponse")
    public Measure updateMeasure(
        @WebParam(name = "arg0", targetNamespace = "")
        Measure arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "mid", targetNamespace = "")
    @RequestWrapper(localName = "deleteMeasure", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.DeleteMeasure")
    @ResponseWrapper(localName = "deleteMeasureResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.DeleteMeasureResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/deleteMeasureRequest", output = "http://soap.dataservice.myhealthylife/DataService/deleteMeasureResponse")
    public long deleteMeasure(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "getPersonByUsername", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetPersonByUsername")
    @ResponseWrapper(localName = "getPersonByUsernameResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetPersonByUsernameResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/getPersonByUsernameRequest", output = "http://soap.dataservice.myhealthylife/DataService/getPersonByUsernameResponse")
    public Person getPersonByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "getPersonByTelegramUsername", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetPersonByTelegramUsername")
    @ResponseWrapper(localName = "getPersonByTelegramUsernameResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetPersonByTelegramUsernameResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/getPersonByTelegramUsernameRequest", output = "http://soap.dataservice.myhealthylife/DataService/getPersonByTelegramUsernameResponse")
    public Person getPersonByTelegramUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.MeasureHystory
     */
    @WebMethod
    @WebResult(name = "measureHistory", targetNamespace = "")
    @RequestWrapper(localName = "getMeasureHistory", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetMeasureHistory")
    @ResponseWrapper(localName = "getMeasureHistoryResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetMeasureHistoryResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/getMeasureHistoryRequest", output = "http://soap.dataservice.myhealthylife/DataService/getMeasureHistoryResponse")
    public MeasureHystory getMeasureHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @return
     *     returns myhealthylife.dataservice.soap.MeasureTypes
     */
    @WebMethod
    @WebResult(name = "measureTypes", targetNamespace = "")
    @RequestWrapper(localName = "getMeasureTypes", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetMeasureTypes")
    @ResponseWrapper(localName = "getMeasureTypesResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetMeasureTypesResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/getMeasureTypesRequest", output = "http://soap.dataservice.myhealthylife/DataService/getMeasureTypesResponse")
    public MeasureTypes getMeasureTypes();

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "getPersonByTelegramId", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetPersonByTelegramId")
    @ResponseWrapper(localName = "getPersonByTelegramIdResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetPersonByTelegramIdResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/getPersonByTelegramIdRequest", output = "http://soap.dataservice.myhealthylife/DataService/getPersonByTelegramIdResponse")
    public Person getPersonByTelegramId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealthylife.dataservice.soap.Current
     */
    @WebMethod
    @WebResult(name = "weatherForecast", targetNamespace = "")
    @RequestWrapper(localName = "getWeatherForecast", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetWeatherForecast")
    @ResponseWrapper(localName = "getWeatherForecastResponse", targetNamespace = "http://soap.dataservice.myhealthylife/", className = "myhealthylife.dataservice.soap.GetWeatherForecastResponse")
    @Action(input = "http://soap.dataservice.myhealthylife/DataService/getWeatherForecastRequest", output = "http://soap.dataservice.myhealthylife/DataService/getWeatherForecastResponse")
    public Current getWeatherForecast(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
