
package myhealtylife.optimalparamters.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OptimalParameters", targetNamespace = "http://soap.optimalparamters.myhealtylife/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OptimalParameters {


    /**
     * 
     * @return
     *     returns myhealtylife.optimalparamters.soap.AgeRangeList
     */
    @WebMethod
    @WebResult(name = "AgeRangeList", targetNamespace = "")
    @RequestWrapper(localName = "readAgeRanges", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadAgeRanges")
    @ResponseWrapper(localName = "readAgeRangesResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadAgeRangesResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readAgeRangesRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readAgeRangesResponse")
    public AgeRangeList readAgeRanges();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns myhealtylife.optimalparamters.soap.ParametersList
     */
    @WebMethod
    @WebResult(name = "parametersList", targetNamespace = "")
    @RequestWrapper(localName = "readOptimalParametersByAgeAndSex", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParametersByAgeAndSex")
    @ResponseWrapper(localName = "readOptimalParametersByAgeAndSexResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParametersByAgeAndSexResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersByAgeAndSexRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersByAgeAndSexResponse")
    public ParametersList readOptimalParametersByAgeAndSex(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns myhealtylife.optimalparamters.soap.ParametersList
     */
    @WebMethod
    @WebResult(name = "parametersList", targetNamespace = "")
    @RequestWrapper(localName = "readOptimalParameters", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParameters")
    @ResponseWrapper(localName = "readOptimalParametersResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParametersResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersResponse")
    public ParametersList readOptimalParameters();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns myhealtylife.optimalparamters.soap.ParametersList
     */
    @WebMethod
    @WebResult(name = "parametersList", targetNamespace = "")
    @RequestWrapper(localName = "readOptimalParametersByNameAgeAndSex", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParametersByNameAgeAndSex")
    @ResponseWrapper(localName = "readOptimalParametersByNameAgeAndSexResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParametersByNameAgeAndSexResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersByNameAgeAndSexRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersByNameAgeAndSexResponse")
    public ParametersList readOptimalParametersByNameAgeAndSex(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealtylife.optimalparamters.soap.Parameter
     */
    @WebMethod
    @WebResult(name = "parameter", targetNamespace = "")
    @RequestWrapper(localName = "createParameter", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.CreateParameter")
    @ResponseWrapper(localName = "createParameterResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.CreateParameterResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/createParameterRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/createParameterResponse")
    public Parameter createParameter(
        @WebParam(name = "arg0", targetNamespace = "")
        Parameter arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealtylife.optimalparamters.soap.Parameter
     */
    @WebMethod
    @WebResult(name = "parameter", targetNamespace = "")
    @RequestWrapper(localName = "updateParameter", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.UpdateParameter")
    @ResponseWrapper(localName = "updateParameterResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.UpdateParameterResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/updateParameterRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/updateParameterResponse")
    public Parameter updateParameter(
        @WebParam(name = "arg0", targetNamespace = "")
        Parameter arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "idParameter", targetNamespace = "")
    @RequestWrapper(localName = "deleteParameter", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.DeleteParameter")
    @ResponseWrapper(localName = "deleteParameterResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.DeleteParameterResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/deleteParameterRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/deleteParameterResponse")
    public long deleteParameter(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealtylife.optimalparamters.soap.AgeRange
     */
    @WebMethod
    @WebResult(name = "AgeRange", targetNamespace = "")
    @RequestWrapper(localName = "createAgeRange", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.CreateAgeRange")
    @ResponseWrapper(localName = "createAgeRangeResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.CreateAgeRangeResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/createAgeRangeRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/createAgeRangeResponse")
    public AgeRange createAgeRange(
        @WebParam(name = "arg0", targetNamespace = "")
        AgeRange arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealtylife.optimalparamters.soap.AgeRange
     */
    @WebMethod
    @WebResult(name = "AgeRange", targetNamespace = "")
    @RequestWrapper(localName = "updateAgeRange", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.UpdateAgeRange")
    @ResponseWrapper(localName = "updateAgeRangeResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.UpdateAgeRangeResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/updateAgeRangeRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/updateAgeRangeResponse")
    public AgeRange updateAgeRange(
        @WebParam(name = "arg0", targetNamespace = "")
        AgeRange arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "idAgeRange", targetNamespace = "")
    @RequestWrapper(localName = "deleteAgeRange", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.DeleteAgeRange")
    @ResponseWrapper(localName = "deleteAgeRangeResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.DeleteAgeRangeResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/deleteAgeRangeRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/deleteAgeRangeResponse")
    public long deleteAgeRange(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns myhealtylife.optimalparamters.soap.ParametersList
     */
    @WebMethod
    @WebResult(name = "parametersList", targetNamespace = "")
    @RequestWrapper(localName = "readOptimalParametersBySex", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParametersBySex")
    @ResponseWrapper(localName = "readOptimalParametersBySexResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParametersBySexResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersBySexRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersBySexResponse")
    public ParametersList readOptimalParametersBySex(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns myhealtylife.optimalparamters.soap.ParametersList
     */
    @WebMethod
    @WebResult(name = "parametersList", targetNamespace = "")
    @RequestWrapper(localName = "readOptimalParametersBySexAngAgeRange", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParametersBySexAngAgeRange")
    @ResponseWrapper(localName = "readOptimalParametersBySexAngAgeRangeResponse", targetNamespace = "http://soap.optimalparamters.myhealtylife/", className = "myhealtylife.optimalparamters.soap.ReadOptimalParametersBySexAngAgeRangeResponse")
    @Action(input = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersBySexAngAgeRangeRequest", output = "http://soap.optimalparamters.myhealtylife/OptimalParameters/readOptimalParametersBySexAngAgeRangeResponse")
    public ParametersList readOptimalParametersBySexAngAgeRange(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
