
package myhealtylife.optimalparamters.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OptimalParamteres", targetNamespace = "http://soap.optimalparamters.myhealtylife/", wsdlLocation = "https://service03-optimalparameters.herokuapp.com/ws/optimal_paramters?wsdl")
public class OptimalParamteres
    extends Service
{

    private final static URL OPTIMALPARAMTERES_WSDL_LOCATION;
    private final static WebServiceException OPTIMALPARAMTERES_EXCEPTION;
    private final static QName OPTIMALPARAMTERES_QNAME = new QName("http://soap.optimalparamters.myhealtylife/", "OptimalParamteres");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://service03-optimalparameters.herokuapp.com/ws/optimal_paramters?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPTIMALPARAMTERES_WSDL_LOCATION = url;
        OPTIMALPARAMTERES_EXCEPTION = e;
    }

    public OptimalParamteres() {
        super(__getWsdlLocation(), OPTIMALPARAMTERES_QNAME);
    }

    public OptimalParamteres(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPTIMALPARAMTERES_QNAME, features);
    }

    public OptimalParamteres(URL wsdlLocation) {
        super(wsdlLocation, OPTIMALPARAMTERES_QNAME);
    }

    public OptimalParamteres(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPTIMALPARAMTERES_QNAME, features);
    }

    public OptimalParamteres(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OptimalParamteres(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OptimalParameters
     */
    @WebEndpoint(name = "OptimalParametersImpPort")
    public OptimalParameters getOptimalParametersImpPort() {
        return super.getPort(new QName("http://soap.optimalparamters.myhealtylife/", "OptimalParametersImpPort"), OptimalParameters.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OptimalParameters
     */
    @WebEndpoint(name = "OptimalParametersImpPort")
    public OptimalParameters getOptimalParametersImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.optimalparamters.myhealtylife/", "OptimalParametersImpPort"), OptimalParameters.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPTIMALPARAMTERES_EXCEPTION!= null) {
            throw OPTIMALPARAMTERES_EXCEPTION;
        }
        return OPTIMALPARAMTERES_WSDL_LOCATION;
    }

}
