
package myhealthylife.sentencegenerator.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SentenceService", targetNamespace = "http://soap.sentencegenerator.myhealthylife/", wsdlLocation = "https://service02-sentencegenerator.herokuapp.com/ws/sentences?wsdl")
public class SentenceService
    extends Service
{

    private final static URL SENTENCESERVICE_WSDL_LOCATION;
    private final static WebServiceException SENTENCESERVICE_EXCEPTION;
    private final static QName SENTENCESERVICE_QNAME = new QName("http://soap.sentencegenerator.myhealthylife/", "SentenceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://service02-sentencegenerator.herokuapp.com/ws/sentences?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENTENCESERVICE_WSDL_LOCATION = url;
        SENTENCESERVICE_EXCEPTION = e;
    }

    public SentenceService() {
        super(__getWsdlLocation(), SENTENCESERVICE_QNAME);
    }

    public SentenceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENTENCESERVICE_QNAME, features);
    }

    public SentenceService(URL wsdlLocation) {
        super(wsdlLocation, SENTENCESERVICE_QNAME);
    }

    public SentenceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENTENCESERVICE_QNAME, features);
    }

    public SentenceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SentenceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Sentences
     */
    @WebEndpoint(name = "SentencesImplPort")
    public Sentences getSentencesImplPort() {
        return super.getPort(new QName("http://soap.sentencegenerator.myhealthylife/", "SentencesImplPort"), Sentences.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Sentences
     */
    @WebEndpoint(name = "SentencesImplPort")
    public Sentences getSentencesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.sentencegenerator.myhealthylife/", "SentencesImplPort"), Sentences.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENTENCESERVICE_EXCEPTION!= null) {
            throw SENTENCESERVICE_EXCEPTION;
        }
        return SENTENCESERVICE_WSDL_LOCATION;
    }

}
